```python
import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from groq import Groq
from github import Github
from config import GROQ_API_KEY, GITHUB_TOKEN

# Create a secure client with the Groq API key
client = Groq(api_key=GROQ_API_KEY)

# Create a secure GitHub client with the GITHUB_TOKEN
gh = Github(GITHUB_TOKEN)

def generate_tests_for_file(file_content: str, filename: str) -> str:
    """Use Groq LLM to generate a complete pytest test file for a given Python file."""
    prompt = f"""You are an expert Python developer. Generate a complete pytest test file for the following Python code.

Rules:
- Write thorough tests for every function and class
- Use pytest fixtures where appropriate
- Include edge cases and error cases
- Add clear docstrings to each test
- Mock external dependencies (APIs, databases, file system)
- Make the tests actually runnable

FILENAME: {filename}

CODE:
{file_content}

Generate ONLY the test code, no explanations:"""

    # Create a secure completion request with the Groq client
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": "You are an expert Python test writer. Output only valid pytest code."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.2,
        max_tokens=2048
    )
    return response.choices[0].message.content


def create_pr_with_tests(repo_url: str, file_path: str, test_content: str, repo_name: str) -> str:
    """Create a new GitHub branch and open a PR with the generated test file."""
    # Get the repository with the specified name
    repo = gh.get_repo(f"snehalogic/{repo_name}")

    # Get the main branch of the repository
    main_branch = repo.get_branch("main")

    # Create a new branch with a secure name
    new_branch = f"codemind/add-tests-{file_path.replace('/', '-').replace('.py', '')}"

    # Create a new git reference for the new branch
    repo.create_git_ref(
        ref=f"refs/heads/{new_branch}",
        sha=main_branch.commit.sha
    )

    # Set the branch permissions to restrict access
    # This is done by setting the branch protection rules
    repo.create_branch_protection(
        new_branch,
        required_status_checks=None,
        required_pull_request_reviews=None,
        restrictions=None,
        allow_force_pushes=False,
        allow_deletions=False,
        block_creations=False
    )

    # Create a new file with the generated test content
    test_filename = f"tests/test_{file_path.split('/')[-1]}"

    try:
        # Update the existing file if it already exists
        existing = repo.get_contents(test_filename, ref=new_branch)
        repo.update_file(
            test_filename,
            f"CodeMind: update tests for {file_path}",
            test_content,
            existing.sha,
            branch=new_branch
        )
    except:
        # Create a new file if it does not exist
        repo.create_file(
            test_filename,
            f"CodeMind: add tests for {file_path}",
            test_content,
            branch=new_branch
        )

    # Create a new pull request with the specified title and body
    pr = repo.create_pull(
        title=f"🧪 CodeMind: Auto-generated tests for {file_path}",
        body=f"""## Auto-generated by CodeMind 🧠

This PR adds automatically generated pytest tests for `{file_path}`.

### What's included:
- Unit tests for all functions and classes
- Edge case coverage
- Mocked external dependencies

> Generated by [CodeMind](https://github.com/snehalogic/codemind)
        """,
        head=new_branch,
        base="main"
    )

    # Set the pull request permissions to restrict access
    # This is done by setting the pull request review rules
    pr.create_review_request(
        reviewers=["snehalogic"],
        team_reviewers=None
    )

    return pr.html_url


def generate_and_pr(repo_url: str, file_relative_path: str) -> dict:
    """Full pipeline: generate tests for a file and open a GitHub PR automatically."""
    # Get the repository name from the repository URL
    repo_name = repo_url.rstrip("/").split("/")[-1]

    # Clone the repository and get the file content
    cloned_path = f"cloned_repos/{repo_name}/{file_relative_path}"
    with open(cloned_path, "r", encoding="utf-8") as f:
        file_content = f.read()

    # Generate tests for the file
    print(f"Generating tests for {file_relative_path}...")
    test_content = generate_tests_for_file(file_content, file_relative_path)
    print("Tests generated!")

    # Create a pull request with the generated tests
    print("Creating PR on GitHub...")
    pr_url = create_pr_with_tests(repo_url, file_relative_path, test_content, repo_name)
    print(f"PR created: {pr_url}")

    return {
        "test_content": test_content,
        "pr_url": pr_url
    }


if __name__ == "__main__":
    result = generate_and_pr(
        repo_url="https://github.com/snehalogic/VoiceVault",
        file_relative_path="backend/inference.py"
    )
    print("\n--- Generated Tests ---")
    print(result["test_content"])
    print(f"\n--- PR URL ---")
    print(result["pr_url"])
```